version: '2.29.1'

services:
  web:
    build: .
    command: python manage.py runserver 127.0.0.1:8000
    volumes:
      - .:/BooksApi
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: BooskApi
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mach1029

volumes:
  postgres_data:
