# Generated by Django 5.0.7 on 2024-07-30 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='complete_name',
            field=models.CharField(default='<django.db.models.fields.CharField><django.db.models.fields.CharField>', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='first_name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='author',
            name='last_name',
            field=models.CharField(max_length=60),
        ),
    ]
