# Generated by Django 5.0.7 on 2024-07-30 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0002_author_complete_name_alter_author_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='complete_name',
        ),
    ]
