# Generated by Django 5.0.7 on 2024-07-30 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0003_remove_author_complete_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(default='Drama', max_length=50),
            preserve_default=False,
        ),
    ]
